"""initial schema -- ports findme_backend's 17 Supabase SQL migrations

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-12

Hand-written (not autogenerated -- no live Postgres in the environment this was built
in) as raw SQL via op.execute(), for the same reason the original schema was hand-written
SQL rather than an ORM-generated one: PostGIS geography columns, GIST indexes, and a
partial unique index need precision autogenerate tooling doesn't reliably produce.

Deliberately dropped versus the Supabase original:
  - Row Level Security policies and BEFORE INSERT/UPDATE triggers (consent transition
    legality, plan-limit enforcement, phone-verification column privileges,
    updated_at-touching) -- all reimplemented in app/services/authz.py and enforced by
    every router going through that layer instead of the database refusing writes on
    its own. This is a real trade-off, not a wash -- see the top-level README's
    "What changed vs the Supabase version" section.
  - storage.buckets / storage.objects policies -- Supabase-specific; replaced by
    app/services/storage.py talking to S3/MinIO directly (bucket ACLs are set at the
    bucket level in docker-compose.yml's minio-init step instead of per-row policies).
  - stripe_customer_id / Stripe-specific columns -- Stripe was already unused (M-Pesa is
    the app's real payment path); not carried forward. See README for why.
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("create extension if not exists postgis")
    op.execute("create extension if not exists pgcrypto")  # gen_random_uuid()

    # ---------- users (merges auth.users + public.profiles) ----------
    op.execute(
        """
        create table users (
            id uuid primary key default gen_random_uuid(),
            email text not null unique,
            hashed_password text not null,
            username text not null unique,
            phone text unique,
            phone_verified boolean not null default false,
            display_name text,
            avatar_url text,
            plan_tier text not null default 'free' check (plan_tier in ('free','plus','pro')),
            plan_renews_at timestamptz,
            referral_code text not null unique,
            created_at timestamptz not null default now(),
            updated_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index users_username_lower_idx on users (lower(username))")
    op.execute("create index users_email_lower_idx on users (lower(email))")
    op.execute("create index users_phone_idx on users (phone) where phone is not null")

    # ---------- refresh_tokens ----------
    op.execute(
        """
        create table refresh_tokens (
            id uuid primary key default gen_random_uuid(),
            user_id uuid not null references users(id) on delete cascade,
            token_hash text not null unique,
            expires_at timestamptz not null,
            revoked_at timestamptz,
            replaced_by_id uuid,
            created_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index refresh_tokens_user_id_idx on refresh_tokens (user_id)")

    # ---------- phone_otps ----------
    op.execute(
        """
        create table phone_otps (
            id uuid primary key default gen_random_uuid(),
            user_id uuid not null references users(id) on delete cascade,
            phone text not null,
            code_hash text not null,
            attempts integer not null default 0,
            expires_at timestamptz not null,
            consumed_at timestamptz,
            created_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index phone_otps_user_id_idx on phone_otps (user_id)")

    # ---------- devices ----------
    op.execute(
        """
        create table devices (
            id uuid primary key default gen_random_uuid(),
            owner_id uuid not null references users(id) on delete cascade,
            nickname text not null,
            device_type text not null default 'phone'
                check (device_type in ('phone','tablet','laptop','router','tracker','other')),
            platform text check (platform in ('ios','android','web','other')),
            is_self_owned boolean not null default true,
            push_token text,
            battery_pct smallint check (battery_pct between 0 and 100),
            last_seen_at timestamptz,
            created_at timestamptz not null default now(),
            updated_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index devices_owner_idx on devices (owner_id)")

    # ---------- consents ----------
    op.execute(
        """
        create table consents (
            id uuid primary key default gen_random_uuid(),
            grantor_id uuid not null references users(id) on delete cascade,
            grantee_id uuid not null references users(id) on delete cascade,
            status text not null default 'pending' check (status in ('pending','active','denied','revoked')),
            scope text not null default 'precise' check (scope in ('precise','city')),
            expires_at timestamptz,
            requested_at timestamptz not null default now(),
            responded_at timestamptz,
            revoked_at timestamptz,
            revoked_by uuid references users(id),
            created_at timestamptz not null default now(),
            updated_at timestamptz not null default now(),
            constraint consents_not_self check (grantor_id <> grantee_id)
        )
        """
    )
    op.execute(
        "create unique index consents_one_live_pair on consents (grantor_id, grantee_id) "
        "where status in ('pending','active')"
    )
    op.execute("create index consents_grantor_idx on consents (grantor_id)")
    op.execute("create index consents_grantee_idx on consents (grantee_id)")

    # ---------- consent_audit_log ----------
    op.execute(
        """
        create table consent_audit_log (
            id uuid primary key default gen_random_uuid(),
            consent_id uuid not null references consents(id) on delete cascade,
            actor_id uuid not null references users(id),
            action text not null check (action in ('requested','approved','denied','revoked')),
            metadata jsonb not null default '{}'::jsonb,
            created_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index consent_audit_log_consent_idx on consent_audit_log (consent_id)")

    # ---------- location_pings ----------
    op.execute(
        """
        create table location_pings (
            id bigint generated always as identity primary key,
            device_id uuid not null references devices(id) on delete cascade,
            recorded_at timestamptz not null default now(),
            location geography(point, 4326) not null,
            accuracy_m real,
            battery_pct smallint check (battery_pct between 0 and 100),
            created_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index location_pings_device_time_idx on location_pings (device_id, recorded_at desc)")
    op.execute("create index location_pings_geo_idx on location_pings using gist (location)")

    # ---------- geofences ----------
    op.execute(
        """
        create table geofences (
            id uuid primary key default gen_random_uuid(),
            device_id uuid not null references devices(id) on delete cascade,
            created_by uuid not null references users(id),
            name text not null,
            center geography(point, 4326) not null,
            radius_m integer not null check (radius_m > 0),
            active boolean not null default true,
            created_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index geofences_device_idx on geofences (device_id)")

    # ---------- geofence_events ----------
    op.execute(
        """
        create table geofence_events (
            id bigint generated always as identity primary key,
            geofence_id uuid not null references geofences(id) on delete cascade,
            device_id uuid not null references devices(id) on delete cascade,
            event_type text not null check (event_type in ('enter','exit')),
            occurred_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index geofence_events_device_idx on geofence_events (device_id, occurred_at desc)")

    # ---------- threat_zones ----------
    op.execute(
        """
        create table threat_zones (
            id uuid primary key default gen_random_uuid(),
            external_id text,
            source text not null,
            category text not null check (category in ('conflict','unrest','disaster')),
            severity text not null check (severity in ('warning','serious','critical')),
            title text not null,
            summary text,
            location geography(point, 4326) not null,
            radius_km real,
            event_date date,
            raw jsonb not null default '{}'::jsonb,
            ingested_at timestamptz not null default now()
        )
        """
    )
    op.execute(
        "create unique index threat_zones_source_external_idx on threat_zones (source, external_id) "
        "where external_id is not null"
    )
    op.execute("create index threat_zones_geo_idx on threat_zones using gist (location)")
    op.execute("create index threat_zones_category_idx on threat_zones (category, severity)")

    # ---------- news_items ----------
    op.execute(
        """
        create table news_items (
            id uuid primary key default gen_random_uuid(),
            source text not null,
            category text not null check (category in ('politics','business','markets','security')),
            headline text not null,
            summary text,
            url text,
            sentiment real check (sentiment between -1 and 1),
            published_at timestamptz not null,
            ingested_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index news_items_published_idx on news_items (published_at desc)")
    op.execute("create index news_items_category_idx on news_items (category)")

    # ---------- watch_topics ----------
    op.execute(
        """
        create table watch_topics (
            id uuid primary key default gen_random_uuid(),
            owner_id uuid not null references users(id) on delete cascade,
            topic_type text not null check (topic_type in ('region','company','keyword')),
            value text not null,
            created_at timestamptz not null default now(),
            unique (owner_id, topic_type, value)
        )
        """
    )

    # ---------- alerts ----------
    op.execute(
        """
        create table alerts (
            id uuid primary key default gen_random_uuid(),
            owner_id uuid not null references users(id) on delete cascade,
            severity text not null check (severity in ('good','warning','critical')),
            category text not null,
            message text not null,
            related_device_id uuid references devices(id) on delete set null,
            related_threat_id uuid references threat_zones(id) on delete set null,
            read boolean not null default false,
            created_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index alerts_owner_idx on alerts (owner_id, created_at desc)")

    # ---------- mpesa_transactions ----------
    op.execute(
        """
        create table mpesa_transactions (
            id uuid primary key default gen_random_uuid(),
            user_id uuid not null references users(id) on delete cascade,
            tier text not null check (tier in ('plus', 'pro')),
            amount_kes integer not null check (amount_kes > 0),
            phone text not null,
            checkout_request_id text not null unique,
            merchant_request_id text,
            status text not null default 'pending' check (status in ('pending', 'success', 'failed')),
            mpesa_receipt_number text,
            result_desc text,
            created_at timestamptz not null default now(),
            completed_at timestamptz
        )
        """
    )
    op.execute("create index mpesa_transactions_user_idx on mpesa_transactions (user_id)")

    # ---------- referrals ----------
    op.execute(
        """
        create table referrals (
            id uuid primary key default gen_random_uuid(),
            referrer_id uuid not null references users(id) on delete cascade,
            referred_id uuid not null unique references users(id) on delete cascade,
            referral_code text not null,
            created_at timestamptz not null default now(),
            constraint referrals_no_self_referral check (referrer_id <> referred_id)
        )
        """
    )
    op.execute("create index referrals_referrer_idx on referrals (referrer_id)")

    # ---------- referral_commissions ----------
    op.execute(
        """
        create table referral_commissions (
            id uuid primary key default gen_random_uuid(),
            referral_id uuid not null unique references referrals(id) on delete cascade,
            referrer_id uuid not null references users(id) on delete cascade,
            referred_id uuid not null references users(id) on delete cascade,
            plan_tier text not null check (plan_tier in ('plus', 'pro')),
            amount_paid_cents integer not null check (amount_paid_cents >= 0),
            commission_cents integer not null check (commission_cents >= 0),
            status text not null default 'pending' check (status in ('pending', 'paid')),
            created_at timestamptz not null default now()
        )
        """
    )
    op.execute("create index referral_commissions_referrer_idx on referral_commissions (referrer_id)")


def downgrade() -> None:
    for table in [
        "referral_commissions",
        "referrals",
        "mpesa_transactions",
        "alerts",
        "watch_topics",
        "news_items",
        "threat_zones",
        "geofence_events",
        "geofences",
        "location_pings",
        "consent_audit_log",
        "consents",
        "devices",
        "phone_otps",
        "refresh_tokens",
        "users",
    ]:
        op.execute(f"drop table if exists {table} cascade")
